[project]
name = "fastapi-learn"
version = "0.1.0"
description = "FastAPI learning application"
readme = "prd.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "alembic",
    "psycopg2-binary",
    "psycopg[binary]",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}
packages = ["config", "routers", "models", "utils"]

[tool.fastapi]
entrypoint = "main:app"
