[project]
name = "fastapi-learn"
version = "0.1.0"
description = "FastAPI learning application"
readme = "prd.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]",
    "alembic",
    "sqlalchemy",
    "psycopg[binary]",
    "pwdlib[argon2]",
    "pydantic[email]",
    "pydantic-settings",
    "pyjwt",
    "fastapi-mail",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "httpx",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "."}
packages = ["config", "routers", "models", "utils"]

[tool.fastapi]
entrypoint = "main:app"